name: Test CMake package

on:
  push:
    branches:
      - master
    tags:
      - v**.**
  pull_request:
    branches:
      - master

jobs:
  build-test:
    env:
        build_profile: clang20d
        conan_preset: clang-20-debug

    strategy:
      fail-fast: false
      matrix:
        simd: [True, False]
        include:
          - simd: True
            cmake_extra: "-DMATHTER_ENABLE_SIMD:BOOL=ON"
          - simd: False
            cmake_extra: "-DMATHTER_ENABLE_SIMD:BOOL=OFF"

    name: SIMD=${{matrix.simd}}
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@v4

    - run: pip install conan

    - name: Install native compilers
      run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update

          sudo apt install gcc-13 g++-13
          sudo update-alternatives --remove-all gcc || true
          sudo update-alternatives --remove-all g++ || true
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 10 --slave /usr/bin/g++ g++ /usr/bin/g++-13

          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17 clang

          sudo update-alternatives --remove-all clang || true
          sudo update-alternatives --remove-all clang++ || true
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 10 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-17

    - name: Cache conan packages
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: ~/.conan2/p
        key: conan-cache-packages-${{env.build_profile}}

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      env:
        PR: "${{github.workspace}}/.github/build_profiles/${{env.build_profile}}"
      run: |
        cmake -E make_directory "${{github.workspace}}/build"
        conan install "${{github.workspace}}" --build=missing -pr $PR -pr:b $PR
        conan cache clean
        cmake -S "${{github.workspace}}" --preset conan-${{env.conan_preset}} ${{matrix.cmake_extra}} -DMATHTER_BUILD_TESTS:BOOL=OFF -DMATHTER_BUILD_BENCHMARKS:BOOL=OFF -DMATHTER_BUILD_EXAMPLES:BOOL=OFF -DMATHTER_VERSION:STRING=99.0.0

    - name: Build & install
      run: |
        cmake --build --preset conan-${{ env.conan_preset }}
        cmake -E make_directory "${{github.workspace}}/install"
        cmake --install ${{github.workspace}}/build/${{env.conan_preset}} --prefix "${{github.workspace}}/install"

    - name: Test package
      shell: bash
      env:
        PR: "${{github.workspace}}/.github/build_profiles/${{env.build_profile}}"
        CMAKE_PREFIX_PATH: "${{github.workspace}}/install"
      run: |
        cmake -E make_directory "${{github.workspace}}/test_package/build"
        conan install "${{github.workspace}}/test_package" --build=missing -pr $PR -pr:b $PR
        conan cache clean
        cmake -S "${{github.workspace}}/test_package" --preset conan-${{env.conan_preset}}
        cmake --build "${{github.workspace}}/test_package/build/${{env.conan_preset}}"
        ${{github.workspace}}/test_package/build/${{env.conan_preset}}/bin/TestMathterPackage
